.catalog:
  name: geocoin
  version: 0.1
  description: geocoin wallet
  uuid: 7c9c38b1-9014-4995-bfe9-d5f053a3aa7d
  minimum_rancher_version: 1.1.3
  questions: #Used to request user input for configuration options
